### ISSUE TITLE
大佬，求qt6 c++开发指南书籍

### ISSUE THREAD

**Issue by yangdianxp** [RivTian/Qt6_Cplusplus-DevelopmentTutorialCode#1]
https://pan.baidu.com/disk/main#/transfer/send?surl=ADoAAAAAABECwg
麻烦大佬了

**Comment by RivTian** [comment]
很抱歉呢，我也没有Qt6的PDF版本，目前是通过实体书进行学习。

**Comment by RivTian** [comment]
@yangdianxp 目前在 Z-Library 中有看到电子版的书籍，网盘链接在此：https://pan.baidu.com/s/1OdyWaE5_1cewHDeOaHouhw?pwd=tian

**Comment by RivTian** [comment]
链接：https://pan.baidu.com/s/1Q0q7t1RFJGFGQSbuKABZaw?pwd=tian 
提取码：tian 
--来自百度网盘超级会员V6的分享
